---
# Source: oes/templates/secrets/opsmx-gitops-secret.yaml
apiVersion: v1
stringData:
  # Repo uri to fetch halyard configuration
  gitcloneparam: https://Rajesh-Sangepu:encrypted%3Agittoken%3Agittoken@github.com/Rajesh-Sangepu/isdmar27.git

  # Repo details to fetch dynamic configuration
  dynamicaccountsgituri: https://github.com/Rajesh-Sangepu/isdmar27.git
  gituser: Rajesh-Sangepu
  gittoken: encrypted:gittoken:gittoken
  dynamicAccRepository: isdmar27

kind: Secret
metadata:
  name: opsmx-gitops-auth
type: Opaque
